[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[scheduled.functions]]
  name = "check-payments"
  cron = "*/2 * * * *"
