[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  external_node_modules = ["tiny-secp256k1"]
  included_files = ["node_modules/tiny-secp256k1/lib/secp256k1.wasm"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[scheduled.functions]]
  name = "check-payments"
  cron = "*/2 * * * *"
